# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: (disabled) Deploy Jekyll with GitHub Pages

# Disabled to prevent conflicts with Vite React deployment.
# Keeping only manual trigger so it doesn't run on push.
on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "disabled-jekyll-pages"
  cancel-in-progress: true

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Jekyll workflow disabled in favor of Vite Pages deploy"
